#!/usr/bin/env python3
"""
Regenerates src/lib/sky/iss-model-data.ts from assets/models/iss.glb.

The model is embedded rather than shipped as an asset because at ~39 KB the
bundle cost is negligible and it removes a whole class of platform-specific
asset-URI bugs. Keeping this generator means the blob is reproducible rather
than something a reader has to take on faith.

Re-download the source model first if you need to:

  curl -L -o assets/models/iss.glb \\
    "https://raw.githubusercontent.com/nasa/NASA-3D-Resources/master/3D%20Models/International%20Space%20Station%20(ISS)%20(A)/International%20Space%20Station%20(ISS)%20(A).glb"

Then:

  python3 scripts/embed-model.py
"""

from __future__ import annotations

import base64
import json
import os
import struct
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "assets", "models", "iss.glb")
TARGET = os.path.join(ROOT, "src", "lib", "sky", "iss-model-data.ts")


def validate(raw: bytes) -> dict:
    """Refuses to embed anything that is not a real glTF 2.0 binary."""
    if len(raw) < 20:
        raise SystemExit("file is too short to be a GLB")

    magic, version, declared = struct.unpack("<4sII", raw[:12])
    if magic != b"glTF":
        raise SystemExit(f"not a GLB: magic was {magic!r}")
    if version != 2:
        raise SystemExit(f"expected glTF 2.0, found version {version}")
    if declared != len(raw):
        raise SystemExit(f"declared length {declared} != actual {len(raw)}")

    chunk_len, chunk_type = struct.unpack("<I4s", raw[12:20])
    if chunk_type != b"JSON":
        raise SystemExit(f"first chunk is {chunk_type!r}, expected JSON")

    return json.loads(raw[20 : 20 + chunk_len])


HEADER = '''/**
 * NASA's International Space Station model, embedded as base64.
 *
 * Source: nasa/NASA-3D-Resources, "International Space Station (ISS) (A)".
 * NASA 3D Resources are released for public use; NASA material is generally not
 * subject to copyright in the United States.
 *
 * Embedded rather than loaded as an asset on purpose: at {kb:.0f} KB the bundle cost is
 * negligible, and it removes the whole class of platform-specific asset-URI
 * bugs — `file://` fetch behaves differently on Android, and the Metro dev
 * server serves a different URI than a release build does. This loads
 * identically everywhere, including under Jest.
 *
 * {meshes} mesh / {primitives} primitives / {materials} materials.
 *
 * Generated by scripts/embed-model.py — do not hand-edit.
 */
'''

FOOTER = '''
/** Decodes the model to an ArrayBuffer for GLTFLoader.parse(). */
export function issModelBuffer(): ArrayBuffer {
  return base64ToArrayBuffer(ISS_GLB_BASE64);
}

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Hermes has `atob`, but its availability has moved between React Native
 * versions and it throws on some inputs; a short decoder is cheaper than
 * discovering that on a device.
 */
export function base64ToArrayBuffer(input: string): ArrayBuffer {
  const clean = input.replace(/=+$/, '');
  const bytes = new Uint8Array(Math.floor((clean.length * 3) / 4));

  let acc = 0;
  let bits = 0;
  let out = 0;

  for (let i = 0; i < clean.length; i++) {
    const value = B64.indexOf(clean[i]);
    if (value === -1) continue;

    acc = (acc << 6) | value;
    bits += 6;

    if (bits >= 8) {
      bits -= 8;
      bytes[out++] = (acc >> bits) & 0xff;
    }
  }

  return bytes.buffer.slice(0, out);
}
'''


def main() -> None:
    if not os.path.exists(SOURCE):
        raise SystemExit(f"missing {SOURCE} — see the docstring for the download command")

    raw = open(SOURCE, "rb").read()
    gltf = validate(raw)

    encoded = base64.b64encode(raw).decode()
    lines = textwrap.wrap(encoded, 100)
    body = "\n".join(f"  '{line}' +" for line in lines[:-1]) + f"\n  '{lines[-1]}';"

    meshes = gltf.get("meshes", [])
    header = HEADER.format(
        kb=len(raw) / 1024,
        meshes=len(meshes),
        primitives=sum(len(m.get("primitives", [])) for m in meshes),
        materials=len(gltf.get("materials", [])),
    )

    with open(TARGET, "w") as f:
        f.write(header)
        f.write("\nexport const ISS_GLB_BASE64 =\n")
        f.write(body)
        f.write("\n")
        f.write(FOOTER)

    print(f"wrote {os.path.relpath(TARGET, ROOT)} from {len(raw)} bytes")


if __name__ == "__main__":
    sys.exit(main())
